# Generated by Django 3.2.16 on 2023-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_filter',
            field=models.CharField(choices=[('1', 'Breakfast'), ('2', 'Lunch'), ('3', 'Dinner')], default='normal', max_length=32),
        ),
    ]
