# Generated by Django 3.2.16 on 2023-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_filter',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='null', max_length=32),
        ),
    ]
