# Generated by Django 3.2.16 on 2023-01-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_category_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_filter',
        ),
    ]
