# Generated by Django 3.2.16 on 2023-01-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default-placeholder_m2h1kl', upload_to='images/'),
        ),
    ]
