# Generated by Django 3.2.16 on 2023-01-22 12:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='../default-user-profile_ximu05', force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[200, 200], upload_to='images/'),
        ),
    ]
